CREATE TABLE jobs
(
    job_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title  VARCHAR2(100) NOT NULL,
    min_salary NUMBER(10, 2),
    max_salary NUMBER(10, 2),
    CONSTRAINT chk_salary CHECK (max_salary - min_salary >= 2000)
);

CREATE TABLE employees
(
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR2(50),
    last_name   VARCHAR2(50),
    job_id      NUMBER,
    manager_id  NUMBER,
    salary      NUMBER(10, 2),
    CONSTRAINT fk_job
        FOREIGN KEY (job_id)
            REFERENCES jobs (job_id)
            ON DELETE CASCADE
);

ALTER TABLE employees
    ADD CONSTRAINT fk_manager
        FOREIGN KEY (manager_id)
            REFERENCES employees (employee_id) ON DELETE CASCADE;

COMMIT;